### PR TITLE
Update GStreamer to 1.20.4

### PR DESCRIPTION
**Pull request by hadess**

### CODE REVIEW

**Comment by barthalion** [comment]
bot, build

**Comment by hadess** [comment]
bot, build

**Comment by hadess** [comment]
https://github.com/flathub/flatpak-builder-lint/issues/54 isn't fixed in Flathub:
```
{
    "errors": [
        "finish-args-redundant-device-all"
    ]
}
If you think problems listed above are a false positive, please report it here:
  https://github.com/flathub/flatpak-builder-lint
```

**Comment by hadess** [comment]
bot, build

**Pull request merged**
